modLoader="javafml"
loaderVersion="[40,)"
license="All Rights Reserved"

[[mods]]
modId="heldshielddr"
version="1.1.2"
displayName="Held Shield DR"
description='''
Gives players and configurable non-player entities passive damage reduction while holding a shield in either hand.
'''

[[dependencies.heldshielddr]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heldshielddr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
