modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="heldshielddr"
version="1.1.1"
displayName="Held Shield DR"
description='''
Gives players and configurable non-player entities passive damage reduction while holding a shield in either hand.
'''

[[dependencies.heldshielddr]]
    modId="neoforge"
    mandatory=true
    versionRange="[21.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.heldshielddr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.1,1.22)"
    ordering="NONE"
    side="BOTH"
